name: main
on: [push]
jobs:
  no-caching:
    runs-on: ubuntu-20.04
    name: no caching
    steps:
      - uses: actions/checkout@v2
      - run: npm -v
      - run: npm ci

  no-caching-yarn:
    runs-on: ubuntu-20.04
    name: no caching yarn
    steps:
      - uses: actions/checkout@v2
      - run: rm package-lock.json
      - run: yarn -v
      - run: yarn install

  npm-install:
    runs-on: ubuntu-20.04
    name: using npm-install
    steps:
      - uses: actions/checkout@v2
      - run: npm -v
      # make sure to use npm command
      - run: rm yarn.lock
      - uses: bahmutov/npm-install@v1

  # experimenting with commands
  # http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/
  npm-install-offline:
    runs-on: ubuntu-20.04
    name: using npm command
    steps:
      - uses: actions/checkout@v2
      - run: npm -v
      # make sure to use npm command
      - run: rm yarn.lock
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --prefer-offline --no-audit

  npm-install-yarn:
    runs-on: ubuntu-20.04
    name: using npm-install with yarn
    steps:
      - uses: actions/checkout@v2
      - run: yarn -v
      # make sure to use yarn command
      - run: rm package-lock.json
      - uses: bahmutov/npm-install@v1
